PYTHON:PYTHON IS A HIGHLY PROGRAMMING LANGUAGE KNOWN FOR ITS SIMPLE SYNTAX AND READABILITY.

WHY PYTHON IS POPULAR:
>IT IS EASY TO LEARN,
>RICH LIBRARIES,
>PALTFORM INDEPENDENT,
>HIGH PAYING JOBS,
>IT IS HAVE A AUTOMATION POWER

APPLICATION
>WEB DEVELOPMENT,
>DATA SCIENCE AND MACHINE LERNING,
>AUTOMATION AND SCRIPTING,
>CYBER SECURITY,
>GAME DEVELOPMENT,
>AI APPLICATION

In [1]:
print("hello bulestock team")

hello bulestock team

VARIABLE:ITS IS A STORE THE DATA

In [23]:
a=10
b=10.5
c="hello"
d=True

In [24]:
print(type(a))
print(type(b))
print(type(c))
print(type(d))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>

OPERATORS:OPERATORS IS A PERFORMED OPERATIONS

In [26]:
a=int(input("enter the a value:"))
b=int(input("enter the b value:"))
print("addition is:",a+b)
print("subtraction is:",a-b)
print("multiplication is:",a*b)
print("division is:",a/b)
print("remainder is :",a%b)
print("a power b:",a**b)
print("floor division is ",a//b)

addition is: 30
subtraction is: -10
multiplication is: 200
division is: 0.5
remainder is : 10
a power b: 100000000000000000000
floor division is  0

INPUT AND OUTPUT

In [7]:
NAME=input("enter your name: ")
print("hello",NAME)

hello shashanth

loops:loops is a repeat code multiple lines

if loop

In [8]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10

while loop

In [9]:
x = 1

while x <= 5:
    print(x)
    x += 1

1
2
3
4
5

condition:conditioons are used in the decision making

if condition

In [27]:
if  100>95:
  print("10 is greater than 5")
  print("it is a valid data")

10 is greater than 5
it is a valid data

In [ ]:
age=18
if age >= 18:
    print("you are eligible to vote")
else:
    print("you are not eligible to vote")

you are eligible to vote

In [28]:
marks = int(input("enter the marks:"))
if marks>=90:
  print("grade A")
elif marks>=80:
  print("grade B")
elif marks>=70:
  print("grade c")
elif marks>=60:
  print("grade D")
else:
  print("fail")

grade B

Functions:Functions are reusable blocks of code.

In [12]:
def add(a, b):
    return a + b
print(add(5, 3))

8

List:A list stores multiple items in a single variable.
Ordered

fetures:Changeable, (mutable),Allows duplicate values

In [29]:
list=['oil','honey','chochalate','biscuits','dry','fruits','cloths']
list.append('shampoo')
print(list)
list.insert(2,"iceceam")
print(list)
list.remove('honey')
print(list)
list.sort()
print(list)

['oil', 'honey', 'chochalate', 'biscuits', 'dry', 'fruits', 'cloths', 'shampoo']
['oil', 'honey', 'iceceam', 'chochalate', 'biscuits', 'dry', 'fruits', 'cloths', 'shampoo']
['oil', 'iceceam', 'chochalate', 'biscuits', 'dry', 'fruits', 'cloths', 'shampoo']
['biscuits', 'chochalate', 'cloths', 'dry', 'fruits', 'iceceam', 'oil', 'shampoo']

Dictionary (dict):A dictionary stores data in key-value pairs

Dictionary Features:
Stores data using keys,
Changeable,
Fast data access,
No duplicate keys

In [34]:
d = {
    "abhi": 1,
    "sai": 2,
    "mahesh": 3,
    "teja": 4,
    "lucky": 5,
    "ravi": 5,
    "raju": 6
}

print(d)
print(type(d))

# Add
d["nikhil"] = 7
print(d)

# Update
d["abhi"] = 101
print(d)

# Multiple update
d.update({"bangairi": 7, "mohan": 8})
print(d)

# Add new key-value pair
d["gopi"] = 102
print(d)

{'abhi': 1, 'sai': 2, 'mahesh': 3, 'teja': 4, 'lucky': 5, 'ravi': 5, 'raju': 6}
<class 'dict'>
{'abhi': 1, 'sai': 2, 'mahesh': 3, 'teja': 4, 'lucky': 5, 'ravi': 5, 'raju': 6, 'nikhil': 7}
{'abhi': 101, 'sai': 2, 'mahesh': 3, 'teja': 4, 'lucky': 5, 'ravi': 5, 'raju': 6, 'nikhil': 7}
{'abhi': 101, 'sai': 2, 'mahesh': 3, 'teja': 4, 'lucky': 5, 'ravi': 5, 'raju': 6, 'nikhil': 7, 'bangairi': 7, 'mohan': 8}
{'abhi': 101, 'sai': 2, 'mahesh': 3, 'teja': 4, 'lucky': 5, 'ravi': 5, 'raju': 6, 'nikhil': 7, 'bangairi': 7, 'mohan': 8, 'gopi': 102}

Class:A class is a blueprint or template for creating objects

In [35]:
class sample:
    def message(self):
     print("hello oops")
obj = sample()
obj.message()

hello oops

Object:an object is a real word entity is an instance of a class.

In [36]:
class student:
    def marks(self,n):
        print(f"maths marks is {n}")
obj=student()
n=int(input("enter the number:"))
obj.marks(n)

obj1=student()
n=int(input("enter the number:"))
obj1.marks(n)

maths marks is 30
maths marks is 45


Inheritance means:

One class gets properties and methods from another class.

In [39]:
class Animal:

    def sound(self):
        print("Animal sound")

class Dog(Animal):

    def bark(self):
        print("Bark")

In [40]:
d = Dog()

d.sound()
d.bark()

Animal sound
Bark

In [41]:
import pandas as pd

In [44]:
df=pd.read_csv('D:/assingments/Pokemon.csv')
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [45]:
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [46]:
df.tail()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   Total       800 non-null    int64
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int64
 12  Legendary   800 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB

In [49]:
df.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000